server:
  port: 17874

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: order
    operations-sorter: order
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: 'interceptor-test-cases'
      paths-to-match: '/**'
      packages-to-scan: com.github.gelald.interceptor
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: ZH_CN
